image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  tag: "{{ .Values.ciTag }}"

secrets: 
  "{{ .Release.Name }}-s":
    type: Opaque
    data: 
      .env: "${{ .Values.secretsJson.PSYNC_ENV }}"

volumes:
  - name: secrets-volume
    secret:
      secretName: "{{ .Release.Name }}-s"
  - name: downloaddir
    emptyDir: {}

volumeMounts:
  - name: secrets-volume
    mountPath: /usr/src/app/.env
    subPath: .env
  - name: downloaddir
    mountPath: /usr/src/app/default_logbook_icon.jpg
    subPath: default_logbook_icon.jpg

initContainers:
  - name: install
    image: alpine
    command:
      - "/bin/sh"
      - -c
    args:
      - >-
        apk update && apk add ca-certificates && update-ca-certificates;
        wget
        -O /download-dir/default_logbook_icon.jpg
        https://raw.githubusercontent.com/paulscherrerinstitute/scilog/main/sci-log-db/src/scilog_config_PSI/default_logbook_icon.jpg;
    volumeMounts:
      - name: downloaddir
        mountPath: "/download-dir"
